import { createAction } from "redux-actions";
import constants from "./constants";

export const loginRequest = createAction(constants.LOGIN_REQUEST);
export const loginSuccess = createAction(constants.LOGIN_SUCCESS);
export const loginError = createAction(constants.LOGIN_ERROR);
export const signupRequest = createAction(constants.SIGNUP_REQUEST);
export const signupSuccess = createAction(constants.SIGNUP_SUCCESS);
export const signupError = createAction(constants.SIGNUP_ERROR);
export const getCategoriesRequest = createAction(constants.GET_CATEGORIES_REQUEST);
export const getCategoriesSuccess = createAction(constants.GET_CATEGORIES_SUCCESS);
export const getCategoriesError = createAction(constants.GET_CATEGORIES_ERROR);
export const getLocationsRequest = createAction(constants.GET_LOCATIONS_REQUEST);
export const getLocationsSuccess = createAction(constants.GET_LOCATIONS_SUCCESS);
export const getLocationsError = createAction(constants.GET_LOCATIONS_ERROR);
export const contactUsRequest = createAction(constants.CONTACT_US_REQUEST);
export const contactUsSuccess = createAction(constants.CONTACT_US_SUCCESS);
export const contactUsError = createAction(constants.CONTACT_US_ERROR);
export const getEventsByCategoryRequest = createAction(constants.GET_EVENTS_BY_CATEGORY_REQUEST);
export const getEventsByCategorySuccess = createAction(constants.GET_EVENTS_BY_CATEGORY_SUCCESS);
export const getEventsByCategoryError = createAction(constants.GET_EVENTS_BY_CATEGORY_ERROR);
export const getEventByIdRequest = createAction(constants.GET_EVENT_BY_ID_REQUEST);
export const getEventByIdSuccess = createAction(constants.GET_EVENT_BY_ID_SUCCESS);
export const getEventByIdError = createAction(constants.GET_EVENT_BY_ID_ERROR);
export const addReviewRequest = createAction(constants.ADD_REVIEW_REQUEST);
export const addReviewSuccess = createAction(constants.ADD_REVIEW_SUCCESS);
export const addReviewError = createAction(constants.ADD_REVIEW_ERROR);
export const addInterestRequest = createAction(constants.ADD_INTEREST_REQUEST);
export const addInterestSuccess = createAction(constants.ADD_INTEREST_SUCCESS);
export const addInterestError = createAction(constants.ADD_INTEREST_ERROR);
export const getUserDataRequest = createAction(constants.GET_USER_DATA_REQUEST);
export const getUserDataSuccess = createAction(constants.GET_USER_DATA_SUCCESS);
export const getUserDataError = createAction(constants.GET_USER_DATA_ERROR);
